Feat/main page
Mao39/airbnb-demo-frontend pull request #1
Opened 2018-01-03 08:33 UTC by Mao39

Desktop-версия main-page Airbnb
Вёрстка на React-компонентах

Женя, прошу оценивать строго, чтобы выпрямлять себе руки:
1) Архитектура непонятная, не знаю как лучше всего выстроить архитектуру, но попытался максимально применять компонентный подход при вёрстке
2) Нэйминг компонентов оставляет желать лучшего
3) Адаптива нет, как уже сказал выше
4) react-fgb не подключал, планируется делать адаптив на нём, flexboxgrid2 временно используется
5) SVG подключены на первое время, подключение SVG оставляет желать лучшего (прошу совета каким методом через react подключать SVG)
6) Какие пути в ссылках задавать также не знаю, поэтому везде "./"
7) Прошу прощения за километровые объявления font-family, так как не прослеживал наследование семейств шрифтов дочерними элементами, будет исправлено
8) Много костылей в вёрстке, планирую исправить
9) prop'сы не использованы при использовании background-image с import'ами, исправлю
10) rem'ы не использованы, во время адаптива буду всё переделывать с пикселей на rem'ы

Надеюсь на остренькую критику и хороший списочек правок

2018-01-04 12:16 UTC, imevro requested changes
Если что непонятно — я всё записал в частые ошибки

2018-01-04 12:16 UTC, evgenyrodionov commented on src/App.js
> +import "./normalize.css";
а зачем ты скачал нормалайз?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +import { Item } from "./Nav";
хуитем

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +export const Copyright = styled.span`
не понял, а куда на экспорт это всё идёт? где будет переиспользоваться?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +                  style={{
бля пиздец, зачем тебе инлайновые стили?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/Nav.js
> +        <Item href="./">Airbnb Citizen</Item>
Поставь # вместо этих ссылок

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/Parametrs.js
> +        <Select value="Русский рубль">Русский рубль</Select>
Российский мб?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Footer/index.js
> +import Parametrs from "./Parametrs";
странное название файла

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Header/SearchBar.js
> +      <Button type="submit" />
это не кнопка

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Experiences/index.js
> +    <React.Fragment>
зачем? если можно просто с section начать?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Experiences/index.js
> +      <section className="experiences">
что за класснейм? у тебя ск должен быть

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +  height: 72px;
зачем задавать ширину? есть паддинги

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +            <Card style={{ backgroundImage: `url(${experiences})` }}>
почему через бэкграунд? Почему не обычным img?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Featured/index.js
> +import { SliderBtn } from "../common/SliderBtn";
что мешает экспортнуть кнопку слайдера из файла Slider?

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/Featured/index.js
> +import { Title } from "../common/Title";
зачем столько компонентов? Если это всё относится к карточке — заведи их все в Card.js и экспорти оттуда

2018-01-04 12:16 UTC, evgenyrodionov commented on src/Main/common/Arrow.js
> +  return <Arrow />;
прокладки не нужны

2018-01-05 07:48 UTC, Mao39 commented
Сделано 95-98% адаптива airbnb-demo-frontend

Заметка:
- Удалена кнопка слайдера, чтобы доделать её не через костыли (закомментирована в коде);
- Весь запланированный объём работы выше я не успел выполнить, что переношу на следующее код-ревью к тебе;
- Прошу меня бить ногами, делать много замечаний и давать советы (пожалуйста);
- Максимально пофикшены те моменты, которые указаны выше тобою. Что не пофикшено: моя невнимательность;
- Много костылей, знаю, очень много тупого и бредового кода, знаю;
- Тут много рефракторить и у меня очень сильно чешутся руки это сделать, все систематизировать нормально наконец-то и убрать костыли.

2018-01-05 10:59 UTC, imevro requested changes

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +import { Link } from "./Service/Nav.js";
сервис? какой сервис?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Footer/Service/Selects.js
> +  -webkit-appearance: none;
в стайлед-компонентс есть автопрефиксер, поэтому достаточно писать `appearance: none`

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Experiences/index.js
> +} from "../Slider.js";
.джс можно опустить это раз

что тайтл карточки или рейтинг делает в слайдере два

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +  height: 72px;
ну и чё?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +const Card = styled.button`
почему это кнопка, кстати? это ссылка

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +import { Head, Caption } from "../Head.js";
ну вот зачем .джс добавил?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Featured/index.js
> +  Price as Name
цена как имя? это как?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Head.js
> +export default { Head, Caption, More, Arrow };
зачем? ты уже экспортнул это всё

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Slider.js
> +  &::-webkit-scrollbar {
убери

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Slider.js
> +  margin-right: -8px;
это что? что мешало row из сетки взять и застилизовать?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Slider.js
> +  padding: 11px;
чё со значением?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Slider.js
> +  margin-top: 153px;
что за меджик намбер?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/Main/Slider.js
> +  left: 1%;
что это?

2018-01-05 10:59 UTC, evgenyrodionov commented on src/index.css
> +@media only screen and (max-width: 768px) {
выкинь

2018-01-06 08:42 UTC, Mao39 commented
Исправления:
- Изменил названия некоторых компонентов по их смыслу;
- Сделал SliderBtn, хоть и костыльно, на переделку пойдёт (делал совместно с ivansedov);
- Удалил лишний мусор из index.css;
- Удалил "магию чисел" и прочий мусор, который являлся костылями;
- Исправил экспорты компонентов (прокладки);
- Обёртки без использования row: добавил row из сетки, дополнительно стилизовал row по необходимости с твоего разрешения;
- Исправлено всё, что ты прислал выше и всё то, что забыл упомянуть в этом списке.

На сегодня:
- Новые правки от тебя;
- Перевод вёрстки на rem/em-систему;
- Корректные SVG;
- fix: props'ы использовать не буду, так как я не шарю, но если посоветуешь их использовать, то гляну доки;
- Тотальный осмотр готовой вёрстки и шлифовка кода, вёрстки (увеличить предсказуемость элементов).

Заранее спасибо, надеюсь на большой список правок, как всегда.

2018-01-06 13:38 UTC, imevro requested changes

2018-01-06 13:38 UTC, evgenyrodionov commented on src/Footer/Primary/Nav.js
> +  display: block;
зачем тебе спан, если ты делаешь дисплей блок? Используй параграф

2018-01-06 13:38 UTC, evgenyrodionov commented on src/Footer/Primary/Selects.js
> +  @media (max-width: 991px) {
без max-width, мобайл фёст и min-width

2018-01-06 13:38 UTC, evgenyrodionov commented on src/Footer/Primary/Selects.js
> +        <Option defaultValue="United States dollar">
а разве не у селекта указывается дефолт вэлью? у опшн вэлью постоянный

2018-01-06 13:38 UTC, evgenyrodionov commented on src/Footer/Primary/index.js
> +    <Service>
а зачем? если есть один контейнер

2018-01-06 13:38 UTC, evgenyrodionov commented on src/Main/Card.js
> +export const Title = styled.div`
тайтл = див?

2018-01-06 19:36 UTC, Mao39 commented
degrade:
- SVG так и остались background'ами, src в imag'ах;
- Props'ы, кроме как в src и url'ах, не использовались [отсылка к следующей неделе];
- ***Вёрстка не переведена на rem'ы/em'ы***;
- Костыль в виде SliderBtn так и остался, хоть и полностью переделан.

*** — до сих пор хочу.

fix:
- Selects и Option: установлены defaultValue и Value;
- Title('ы): по семантике и по смыслу, исходя из блочной модели, заменены на параграфы;
- MobileFirst: переделал медиа-запросы, добавил больше адаптива шрифтам в вёрстке;
- More friendly adaptive: пошлифовал вёрстку в плане адаптива, доводя адаптив до нормального состояния на всех разрешениях экрана;
- Было исправлено много других мелких косяков и проёбы со шрифтами (не везде то, что в макете).

Женя-сан, принимай!

2018-01-07 12:57 UTC, imevro approved these changes

2018-01-07 12:57 UTC, merged