Homes-page Airbnb-demo — Junior's work
Mao39/airbnb-demo-frontend pull request #2
Opened 2018-01-11 08:36 UTC by Mao39

# Homes-page Airbnb-demo — Junior's work

### Исправлено:
- Адаптив хедера, футера (Селектов);
- Исправлены fail'ы адаптива карточек Explore на Main-page;
- Удалены инлайн-стили в иконках, перешли на пропсы.

### Сделано:
- Desktop, Tablet, Mobile страница списков домов;
- Изменения в архитектуре приложения;
- React-router-dom;
- Google-map-react;
- React-dates (/omit/), devDependencies -> moment;
- Фильтр дат;
- Демонстрация подключения библиотеки с базовыми настройками;
- Отверстаны фильтры Room type (существует только на Desktop) и Guests (на всех разрешениях) — не рабочие.

### Заметка:
- Некоторые части кода закомментированы (например: свойства для скрытых фильтров);
- Фильтр дат: выбор дат, отображение их в контенте кнопки, разные состояния кнопки, оверлей при открытии;
- Будет доделано в фильтре: Reset, Save, Close, react-transition, заблокированные даты в календаре;
- Будет доделано везде: интерактивность элементам, outline, интерактивные элементы с cursos-pointer, hover'ы и прочий UI.

Всё внимание было сосредоточено на работу со state'ами и props'ами, фильтром дат.

### Ссылка на now.sh: 
[airbnb-demo-frontend
](https://furmand-ruoggbblrn.now.sh/)
<br/>

**Женя, как всегда, прошу жести и рекомендаций, пожалуйста!**

2018-01-11 20:46 UTC, evgenyrodionov commented
Чё так распидорило
![image](https://user-images.githubusercontent.com/775692/34846550-8c6bc2d6-f729-11e7-9be3-5e171fec2e9b.png)

---

Тайтлы маленькие
![image](https://user-images.githubusercontent.com/775692/34846576-9b37dfca-f729-11e7-812a-d1ac9926460f.png)

---

![image](https://user-images.githubusercontent.com/775692/34846585-a8611f9a-f729-11e7-9950-b46561058b4e.png)

---

Карта вниз ушла и шрифты у пагинации тонкие
![image](https://user-images.githubusercontent.com/775692/34846598-b035633e-f729-11e7-8c69-3b7cc14cc908.png)

2018-01-11 20:47 UTC, evgenyrodionov commented
У фильтров бордеры слишком светлые бтв

2018-01-11 20:58 UTC, imevro requested changes

2018-01-11 20:58 UTC, evgenyrodionov commented on package.json
> +    "react-onclickoutside": "^6.7.0",
выбери одну

2018-01-11 20:58 UTC, evgenyrodionov commented on package.json
> +    "omit": "^1.0.1",
lodash/omit мб?

2018-01-11 20:58 UTC, evgenyrodionov commented on package.json
> +    "moment": "^2.20.1",
зачем это в девдепс?

2018-01-11 20:58 UTC, evgenyrodionov commented on package.json
> +    "react-addons-shallow-compare": "^15.6.2"
а это зачем?

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Footer/Icon.js
> +  return <Icon href="#" />;
читай частые ошибки первого этапа про компоненты-прокладки

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Footer/Secondary.js
> +import logo from "../UI/footerLogo.svg";
ты и так в футере, нах ты это туда перетащил?

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Footer/Secondary.js
> +  background-image: url(${facebook});
зачем? есть же имейдж

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Header/index.js
> +  & > .container {
фу пиздец

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Header/index.js
> +    & > .container {
ужасно

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Header/index.js
> +    & > .container {
нельзя так стилизовать

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +import omit from "lodash/omit";
лол, как ты импортишь из лоудэш/омит, если у тебя в пекейджджсон прописан пакет омит?

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +            : isOpen ? "Check in — Check out" : "Dates"}
вложенные тернарники? пиздец

вынеси в функцию, которая будет возвращать нужный текст и передавай в нее значения

2018-01-11 20:58 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  onFocusChange(focusedInput) {
объявляешь позже чем используешь

2018-01-12 08:46 UTC, Mao39 commented
**Женя, большущая благодарность тебе за ревью моего кода, за щепетильность в ревью проекта и за ревью кода других ребят!**


## Fix:
- Ссылки в навигации хедера переведены с flex-свойства space-around на margin-left, фиксируя отступы между ними;
- Пофиксил размеры шрифтов у заголовков секций/карточек на главной странице;
- Удалил бесполезный контейнер, что пофиксило колонку на странице списка домов;
- Пофиксил "уходящую вниз" GoogleMap;
- Сделал шрифты у пагинации (самих кнопок) жирнее, **но в макете** `font-weight: book`!
- Borders кнопок фильтра сделаны темнее, но **по макету они таки светлее**.
- Удалил неиспользуемые пакеты;
- Удалил СК-прокладку;
- Переместил "редкие" svg-изображения, которые используются только в определенных компонентах (хедер и футер) в их директории;
- Заменил иконки в футере на переиспользуемые Link'и + изображениями внутри;
- Переместил функции выше до их вызова (хотя они и работали, а также функции ниже делали читаемость кода выше, ИМХО);
- Вынес тернарник с выводом контента в отдельную функцию, в которой вложенные тернарники для читаемости разложил на обычные if/else if/else;
- Удалил react-addons-shallow-compass (не знаю откуда он взялся, видимо вместе с установкой всех devЗависимостей для react-dates);
- Заменил Тайтл и favicon приложения;
- Переустановил lodash, нормально импортировал omit из него, переустановил omit, убрав его из devDep;
- Пофиксил передачу чисел, где стояла передача строкового типа + тернарник на выдачу строк с кроватями;
- Переделал ссылки на главной страницы у SeeAll на роутинг-ссылки, ссылка с секции Homes ведёт на Homes-page;
- Пофкисил margin-top'ы у SliderBtn в секциях на главной странице, но это костыль (если можно, прокомментируй);
- Везде доделал cursor: pointer (отсутствовал у dropdown-кнопки у логотипа на tablet/mobile разрешениях).

## Not fixed/for approval:
- Ужасная стилизация контейнера из сетки (согласование по переписке, будет исправлено до следующего ПРа);
- Не выкатывал мне в ошибки, но я захотел поменять  `this.setState(() => ({ isOpen: !this.state.isOpen }))` на `this.setState(prevState => ({ isOpen => !prevState.isOpen }))` и у меня не выходит. Согласование по переписки too.

## To fix:
- То что остаётся на согласовании;
- Динамичный Title страниц;
- Циклы для вывода повторяющихся компонентов;
- SliderBtn (посмотришь — поймёшь);
- Hover'ы, active'ы, focus'ы, outline'ы, pointer'ы (поинтеры сделаны по максималкам, но пройтись ещё раз надо) и прочий интерактив;
- Поставить фильтру дат неактивные даты;
- Переключение пагинации;
- react-transition;
- См. "послесловие".
 
**На согласование, не пофикшено!**

Фильтр дат доделать полностью, естественно.

Для сегодняшнего ПРа сделано достаточно мало, в течении дня (до завтрашнего ПРа) в планах выполнить всё то, что запланировано в первом комментарии + вынести стэйты в общий родительский контейнер, сделать фильтр с гостями и выбора типа комнат;

**Ссылка на now.sh:**
[airbnb-demo-frontend](https://furmand-nxwsqcxzth.now.sh/)

2018-01-12 14:06 UTC, imevro requested changes

2018-01-12 14:06 UTC, evgenyrodionov commented on package.json
> +        "moment": "^2.20.1",
откуда 8 пробелов взялось?

2018-01-12 14:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  renderBtnInfo = (startDateString, endDateString) => {
вынеси отсюда в отдельную функцию, не храни в классе — незачем

2018-01-12 14:06 UTC, evgenyrodionov commented on src/Homes/List/index.js
> +              <div className="col-xs-12 col-sm-6 col-md-6">
mobile first — что что объявлено ниже, соблюдается пока не будет другого (если ты объявил см-6, то нет нужды мд-6)

2018-01-13 08:49 UTC, Mao39 commented
**Женя, благодарность за код-ревью!**

## Выполненная задача до данной проверки:
Стилизована мобильная версия фильтра дат.

## Fix-list:
- Исправлен кривой заголовок календаря с днями недели за счёт line-height;
- Добавил функции (helper.js), отвечающих за блокирование прошедших дат в календаре; взяты из официальных примеров репозитория react-dates;
- Убрал бесполезные классы сетки;
- Подчистил пробелы в package.json.

Большинство своих ошибок знаю (крупные тоже), до проверки ПРа не хватило времени всё подшлифовать (основное время убил на приоритетную задачу), что было задумано, поэтому остаётся до дедлайна (коммиты будут моими свидетелями). Например, выше комментарий про вынесение в отдельную функцию ещё не исполнил, так как планирую переписать подобный код для улучшения читабельности.
Задача на сегодня — доделать всё, причесать код, убрать много лишнего мусора из кода.

**Ссылка на now.sh:**
[airbnb-demo-frontend](https://airbnb-demo-build-qbqeswxjpx.now.sh/)

2018-01-13 09:00 UTC, evgenyrodionov commented
Отступы в карточках, шрифты в футере
![image](https://user-images.githubusercontent.com/775692/34904564-46b986a2-f859-11e7-8c94-4a10595980f2.png)

2018-01-13 09:01 UTC, evgenyrodionov commented
Слиплось же
![image](https://user-images.githubusercontent.com/775692/34904566-51c1ca5a-f859-11e7-9cb9-8e55e6f12ee1.png)

Втф
![image](https://user-images.githubusercontent.com/775692/34904567-5d44681a-f859-11e7-9fa2-bdf5674436af.png)

Блевотный формат
![image](https://user-images.githubusercontent.com/775692/34904573-6aea2f36-f859-11e7-8c3d-f0ba377d5991.png)

2018-01-13 09:04 UTC, imevro requested changes

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  onFocusChange = this.onFocusChange.bind(this);
читай частые ошибки

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  renderBtnInfo = (startDateString, endDateString) => {
ну и чё бля?

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  }
зачем это методом в классе, почему не может быть просто константой?

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +          {isOpen ? this.filter : null}
что такое this.filter?

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +                    : matchMedia("(min-width: 576px)").matches ? 1 : 12
блядь, ты опять плодишь ебучее дерево из тернарников

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +                  matchMedia("(min-width: 576px)").matches
в константу вынеси вызов и используй

2018-01-13 09:04 UTC, evgenyrodionov commented on src/Homes/Filters/helper.js
> +function isBeforeDay(a, b) {
зачем это тебе вообще (это раз)
почему файл называется helper, если их тут два (это два)

2018-01-13 20:52 UTC, Mao39 commented
Женя, предоставляю на проверку! Ниже не полный список проделанной работы за сегодня.

## Fix-list/do-list:
- Fix шрифтов в футере (font-weight: bold на book/600) списка домов;
- Поправил имена пропов в карточках на главной странице для кол-ва отзывов;
- Отступы между строк в карточках сделаны в точности, как на макете (поясню за каждый пиксель);
- Удалил max-width у изображений на главной;
- Поднял заголовок недели выше в календаре;
- Исправил формат дат в фильтре дат;
- Прочесал код в фильтре, вынес всё за класс и удалил прочий мусор;
- Адаптивный календарь, фильтр выбора дат, исправлены баги;
- Исправил косяк пагинации на разрешении 320px (из-за padding'ов);
- Установил scrolllock и использовал его по назначению для мобильной версии фильтра выбора дат;

**Ссылка на деплой:**
[airbnb-demo-frontend](https://build-lvsnikvyuv.now.sh/)

2018-01-20 08:57 UTC, Mao39 commented
С предыдущего ПРа на проверку изменений практически никаких, кроме сырого фильтра гостей, который недоступен.

Ссылка на проект:
[airbnb-demo-frontend](url)

2018-01-21 07:55 UTC, imevro requested changes

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +const scrollLock = isOpen => {
почему функция не названа как компонент?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    if (isOpen) return <ScrollLock />;
а что мешало использовать &&?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +const lastDays = day => !isInclusivelyAfterDay(day, moment());
ласт дейс что? неочевидный нейминг

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  toggleOpening = () => {
toggle opening? опенинг чего? нового тайтла анимэ?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +              <ScrollLock />
ты же выше вынес это в отдельную эээ функцию?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +            ) : null
чтобы не плодить нуллы и тернарники, используй conditional rendering через &&, об этом сказано в документации реакта

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +    props.type !== "adult" && props.removeActive > 0 ? "1" : ".5"};
ну охуеть, а если мы завтра другой тип передадим, будешь условия плодить тут? так дело не пойдет, твой компонент бракованный

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +const HumanCoast = props => {
East Coast West Castoums? что такое Coast?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +    guest_children: 0,
camelCase

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +      return true;
true что? зачем это возвращать?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +    if (this.state[`guest_${type}`] > 1) {
нахуя тебе в Guests все эти префиксы guests, если ты потом вот такую хуйню вытворяешь вместо `this.state[type]`?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +                addGuest={this.addGuest}
ну ты и так в Guests, зачем все эти постфиксы, почему нельзя просто `add={this.add}`?

2018-01-21 07:55 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +                removeActive={this.removeGuest}
чем отличается removeGuest от removeActive?

2018-01-21 17:32 UTC, Mao39 commented
## fix-list/do-list:
- Исправил ошибки выше;
- Сменил ущербный нэйминг функций (некоторые названия избыточны, но так понятнее);
- Подправил нэйминг компонентов в фильтрах;
- Устранил очень старые ошибки, относятся к убогой стилизации контейнеров от сетки;
- Обновил flexboxgrid2;

**Ссылка не деплой:**
[airbnb-demo-frontend](url)

2018-01-22 14:34 UTC, imevro requested changes

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Header/index.js
> +    background: url(/static/media/dropdownArrow.b2745bbd.svg) no-repeat center;
почему ты так сделал? через реквайр надо

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  const endDateString = formatEndDate(endDate);
а зачем постфиксы стринг?

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  return !matchMedia("(min-width: 576px)").matches && isOpen && <ScrollLock />;
ещё раз повторяю: если ShowScrollLock это компонент, почему он именуется в camelCase?

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +    this.state[type] > 1 &&
ты про ифы вообще забыл? это что вообще тут происходит?

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +  addNumberGuests = type => {
опять повторяю вопрос — зачем постфиксы гуестс, если ты и так в гуестс?

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +      [type]: this.state[type] + 1
prevState же тебе нужен

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +                removeActive={this.removeGuest}
ну и?

2018-01-22 15:41 UTC, Mao39 commented
Исправлены ошибки и замечания, указанные тобою выше.

**Ссылка на деплой:**
[airbnb-demo-frontend](https://build-nqtryrqgzx.now.sh/)

2018-01-22 19:39 UTC, imevro approved these changes

2018-01-22 19:39 UTC, merged