Data from API -> Objects of rooms / houses
Mao39/airbnb-demo-frontend pull request #6
Opened 2018-02-01 07:56 UTC by Mao39

## fix/do-list:
- Запросил данные с AP. В соответствии с этими данными происходит рендеринг объектов на главной странице и на странице списка Homes;
- Во время разработки были замечены проблемы в вёрстке слайдеров на главной странице. 
Исправил (Slider, Section, SliderBtn);

Не успел сделать skeleton-placeholder с dummy-карточками/информацией для первичного рендеринга.

**Ссылка на деплой:**
[airbnb-demo-frontend](https://build-dvsyvbazmu.now.sh/)

2018-02-01 16:37 UTC, imevro requested changes

2018-02-01 16:37 UTC, evgenyrodionov commented on src/Homes/Card.js
> +  if (kind === 'private_room') return 'Private room';
это что? объекты используй

2018-02-01 16:37 UTC, evgenyrodionov commented on src/Main/Homes/index.js
> +  state = { items: [] };
хуитемс))))

2018-02-02 07:59 UTC, Mao39 commented
Исправил твои замечания.
С Хероку не вышло, поэтому деплой на now, по традиции.

**Ссылка на деплой:**
[airbnb-demo-frontend](https://build-ivizsvcbzj.now.sh/)
Там карта немного полетела при сборке, возможности передеплоить нет (3G-интернет).

2018-02-03 10:27 UTC, imevro approved these changes

2018-02-03 10:28 UTC, merged